- name: Install GNOME Desktop
  shell: |
    apt install gdm3 -y
    tasksel install ubuntu-desktop
    systemctl restart gdm3
  when: os_gui=="gnome"

- name: Install KDE Desktop
  shell: |
    add-apt-repository ppa:kubuntu-ppa/backports -y
    apt-get update
    apt install sddm 
    apt-get install kubuntu-desktop -y
  when: os_gui=="kde"
  
- name: Install Xfce Desktop
  shell: |
    apt install xfce4 xfce4-goodies -y
  when: os_gui=="xfce"

- name: Config Desktop
  shell: |
    systemctl set-default graphical.target
    systemctl isolate graphical.target
    systemctl get-default