- name: Install GNOME Desktop
  shell: |
    apt-get install gnome-session-flashback -y
    apt install ubuntu-desktop gnome-panel gnome-settings-daemon metacity nautilus gnome-terminal -y
  when: os_gui=="gnome"

- name: Install KDE Desktop
  shell: |
    add-apt-repository ppa:kubuntu-ppa/backports -y
    apt-get update
    apt install sddm 
    apt-get install kubuntu-desktop -y
  when: os_gui=="kde"
  
- name: Install Xfce Desktop
  shell: |
    apt install xfce4 xfce4-goodies -y
  when: os_gui=="xfce"

- name: Config Desktop
  shell: |
    systemctl set-default graphical.target
    systemctl isolate graphical.target
    systemctl get-default