- name: Install GNOME Desktop
  shell: |
    apt update && apt upgrade -y
    apt-get install gdm -y
    apt-get install gnome-session-flashback -y
    apt install ubuntu-desktop gnome-panel gnome-settings-daemon metacity nautilus gnome-terminal -y
  when: os_gui=="gnome"

- name: 
  shell: |
    touch .xsession
    echo gnome-session > ~/.xsession
  when: os_gui=="gnome"  

- name: Allow root login
  lineinfile:
    dest: /etc/pam.d/gdm-autologin
    regexp: 'auth   required        pam_succeed_if.so user != root quiet_success'
    state: absent
  when: os_gui=="gnome"

- name: Allow root login
  lineinfile:
    dest: /etc/pam.d/gdm-password
    regexp: 'auth    required        pam_succeed_if.so user != root quiet_success'
    state: absent
  when: os_gui=="gnome"

- name: Install KDE Desktop
  shell: |
    add-apt-repository ppa:kubuntu-ppa/backports -y
    apt update && apt upgrade -y
    apt install plasma-desktop -y
    apt install kde-full -y
    apt install kde-standard -y
    apt install kde-plasma-desktop
  when: os_gui=="kde"
  
- name: Allow root login
  lineinfile:
    dest: /etc/pam.d/sddm
    regexp: 'auth    required        pam_succeed_if.so user != root quiet_success'
    state: absent
  when: os_gui=="kde"

- name: Install Xfce Desktop
  shell: |
    apt install xfce4 xfce4-goodies -y
  when: os_gui=="xfce"

- name: Clear Warning message
  lineinfile:
    dest: /root/.profile
    regexp: 'mesg n || true'
    line:  'tty -s && mesg n || true'
    backrefs: yes

- name: Config Desktop
  shell: |
    systemctl set-default graphical.target
    systemctl isolate graphical.target
    systemctl get-default