- name: Install GNOME Desktop
  shell: |
    apt install -y gnome-shell ubuntu-gnome-desktop
    apt install -y unity-tweak-tool gnome-tweak-tool
    dpkg-reconfigure lightdm
  when: os_gui=="gnome"

- name: Install KDE Desktop
  shell: |
    apt install sddm
    apt install tasksel
    tasksel install kubuntu-desktop
    dpkg-reconfigure sddm
  when: os_gui=="kde"
  
- name: Install Xfce Desktop
  shell: |
    apt install xfce4 xfce4-goodies -y
  when: os_gui=="xfce"

- name: Config Desktop
  shell: |
    systemctl set-default graphical.target
    systemctl isolate graphical.target
    systemctl get-default