- name: Install Desktop on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- name: Install VNC server and configure it
  include: vnc.yml
  when: os_connection=="vnc"

- name: Install remote xrdp server 
  include: vnc.yml
  include: remote.yml
  when: os_connection=="remote"

