# install VNCSERVER by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- name: Create vncserver System User
  user:
    name: vnc
    shell: /bin/bash
    home: /home/vnc
    create_home: yes

- name: 
  shell: |
    su vnc
    vncpasswd
    
    exit
   
# configure and start vncserver.service
- block:
  - name: Setting vncserver service
    copy:
      src: vncserver.service
      dest: /lib/systemd/system/vncserver.service

  - name: Restart vncserver
    service:
      name: vncserver
      state: restarted
      enabled: yes

# set soft link, -f enforce the exist links
# ln -sf src des
- name: set soft link
  shell: ln -sf /lib/systemd/system/vncserver.service /lib/systemd/system/vnc.service
    
# Check version,
# must use sudo sh -c to solve the no-root permission
- name: Check vncserver Version
  shell: sudo sh -c "vncserverctl status | grep 'VNCSERVER version' 1>> /data/logs/install_version.txt"

# check service state
- name: Check vncserver Service
  shell: systemctl status vncserver | grep Active*
  register: check_vncserver_service
  notify: check_vncserver_service
