- block:
  - name: Install Remote tool on {{ansible_os_family}}
    shell: |
      yum install xrdp -y
      systemctl start xrdp
      systemctl enable xrdp
    when: ansible_os_family == "RedHat"

  - name: Install VNC Server on {{ansible_os_family}}
    shell: |
      apt install xrdp -y
      systemctl start xrdp
      systemctl enable xrdp
    when: ansible_os_family == "Debian"

# check service state
  - name: Check xrdp Service
    shell: systemctl status xrdp | grep Active*
    register: check_xrdp_service
    notify: check_xrdp_service